version: '3.3'
services:
  k8s:
    image: noirfate/vul-k8s-cve-2021-25735:1.0
    ports:
      - "12222:22"
    environment:
      - LC_CTYPE=en_US.UTF-8
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime
